server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
        - id: descuentoGrupo-service
          uri: lb://descuentoGrupo-service
          predicates:
            - Path=/descuentoGrupo/**
        - id: descuentoVisitas-service
          uri: lb://descuentoVisitas-service
          predicates:
              - Path=/descuentoVisitas/**
        - id: tarifa-service
          uri: lb://tarifa-service
          predicates:
              - Path=/tarifa/**
        - id: reserva-service
          uri: lb://reserva-service
          predicates:
              - Path=/reserva/**